date.timezone = Asia/Shanghai
memory_limit = 128M
max_execution_time = 300
max_input_time = 60
post_max_size = 50M
upload_max_filesize = 50M
expose_php = Off
opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 0

