apiVersion: v1
kind: Secret
metadata:
  name: mcskin-secrets
  namespace: mcskin-migration
type: Opaque
stringData:
  APP_KEY: replace-me
  DB_DATABASE: mcskin
  DB_USERNAME: mcskin
  DB_PASSWORD: replace-me
  OSS_ACCESS_ID: replace-me
  OSS_ACCESS_KEY: replace-me
  OSS_BUCKET: replace-me
  OSS_ENDPOINT: replace-me
  OSS_SSL: "true"
  JWT_SECRET: replace-me

